version: "3.7"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
      - "33600:33600"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  php-fpm:
    image: clubdeuce/php-fpm:7.3
    volumes:
      - ./www:/var/www
      - ./docker/files/etc/php/mailhog.ini:/etc/php7/conf.d/mailhog.ini
  web:
    image: nginx:1.17.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./docker/files/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes: 
  db_data: {}